import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { eq } from "drizzle-orm";
import * as schema from "../src/lib/db/schema";

// Check for DATABASE_URL
if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL environment variable is not set");
  process.exit(1);
}

const sql = neon(process.env.DATABASE_URL);
const db = drizzle(sql, { schema });

// Inflatable descriptions and specifications from the old site
const inflatableUpdates = [
  // 13x13 Bouncers
  {
    slug: "dora-the-explorer",
    description: "Grab your backpack and map! Join Dora and friends on their next expedition in this 13' x 13' Dora the Explorer bounce house. Boots, the monkey, can help girls and boys solve the mystery. Designed for hours of entertaining, educational play!\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "batman",
    description: "A comic book fan's fantasy come true! With gorgeous artwork, this 13' x 13' Batman bounce house will keep fans coming back for more. Batman and Robin team up with villains Harley Quinn and Bane featured on the artwork.\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "the-incredibles",
    description: "Team up with The Incredibles in their fight against crime! Mr. Incredible, Elastigirl and their three incredible kids, Violet, Dash and little Jack Jack, are a family of undercover superheroes.\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "spongebob",
    description: "Visit your favorite pineapple under the sea! Spend hours jellyfishing in the warm waters of Bikini Bottom with SpongeBob, Patrick and Squidward.\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "disney-princess",
    description: "A fairytale come true, our Disney Princess bounce house is perfect for any occasion. Features beloved characters including Cinderella, Snow White, Sleeping Beauty, Belle, Jasmine, and Ariel.\n\nExcellent for smaller kids looking for a simple bounce house rental and imaginative play.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "happy-birthday",
    description: "Go wild! Our 13' x 13' animal themed birthday bounce house is perfect for boys and girls of all ages. Features forest and jungle creatures celebrating together.\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "halloween",
    description: "This 13' x 13' Halloween-themed bounce house features festive characters like bats, owls, trick-or-treaters, Dracula, a witch, and the Mummy. Perfect for letting your little goblins burn off that sugar!\n\nExcellent for smaller kids looking for a simple bounce house rental. Works great indoors during cooler months with adequate space.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "happy-haunting",
    description: "Jump into the Halloween spirit with our 13' x 13' Happy Haunting bounce house. Features happy trick-or-treaters on their way out for some candy dressed as a witch, Frankenstein, a mummy and Dracula. Perfect for a Halloween party – either inside or outside – our Happy Haunting bounce house is sure to be a hit!\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "its-a-girl-thing",
    description: "This 13' x 13' bounce house is perfect for your princess's get together. Covered in bright colors and a bit of sparkle, your little princess and her friends are greeted by a pair of stylish young ladies, ready to play dress-up with makeup, shoes, bags, hearts and flowers.\n\nPerfect for birthday celebrations and tea parties. Excellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "trucks",
    description: "On your mark, get set, go! Our 13' x 13' dirt bike and truck bounce house is perfect for gatherings of all sizes! This inflatable works wonderfully for children who love monster trucks and racing themes, offering extended entertainment through jumping and imaginative play.\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "celebrate",
    description: "Let's jump! This 13' x 13' Celebrate bounce house is sure to be the hit of your party. Perfect for birthdays, religious celebrations, neighborhood gatherings, and other events.\n\nExcellent for smaller kids looking for a simple bounce house rental.",
    width: "13'",
    length: "13'",
    height: "13'",
    spaceRequired: "18' x 18'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },

  // Castle Bouncers
  {
    slug: "basic-castle",
    description: "Jersey Jumpy's large Excalibur Castle bounce house is 360-degrees of brilliant and joyful regal fun for all young royalty. Features vibrant colors—blue, red, yellow, orange, and green—along with four tall spires, making it suitable for royal-themed celebrations.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "military-truck",
    description: "This bounce house is great for boys and girls of all ages. Let the fun begin when your kids jump into this Military Truck bounce house! The unit provides entertainment for backyard parties and large events, featuring camouflage decoration that appeals to children of various ages.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-9 kids",
    capacityAges7to10: "5-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "excalibur-castle",
    description: "Jersey Jumpy's Excalibur Castle is 360-degrees of brilliant and joyful regal fun for all young royalty. This 15' x 15' bounce house features royal theming with blue, red, yellow, orange, and green colors, plus four tall spires designed to create a majestic castle experience.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-9 kids",
    capacityAges7to10: "5-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "funhouse-castle",
    description: "Our Funhouse Castle bounce house is perfect for any celebration! Let the fun begin when your Prince or Princess jumps into the castle. This 15' x 15' inflatable features blue, red, and yellow colors with four tall spires. It accommodates various age groups for hours of entertainment at backyard parties or larger events.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-9 kids",
    capacityAges7to10: "5-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "sizzling-castle",
    description: "Our Sizzling Castle bounce house is red hot! Perfect for any summer day or celebration! Features vibrant blue, red, and yellow colors with four tall spires, making it ideal for royal-themed parties and backyard events.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-9 kids",
    capacityAges7to10: "5-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "cutting-edge-castle",
    description: "Calling all Knights and Ladies! Get out your best armor and get to jumping in our Cutting Edge Castle bounce house. This 15' x 15' blue and gray inflatable combines medieval charm with modern bounce house fun. It encourages healthy exercise while transporting guests back in time.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-9 kids",
    capacityAges7to10: "5-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "birthday-cake",
    description: "Jersey Jumpy's 15' x 15' birthday cake bounce house is the grandest, most spectacular birthday cake ever made. Features two tiers decorated with icing, four illuminated candles, and side panels adorned with confetti and balloon artwork.",
    width: "15'",
    length: "15'",
    height: "17'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-9 kids",
    capacityAges7to10: "5-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "in-and-out-jumpbox",
    description: "Our 10'x10' In-And-Out Jumpbox is perfect for smaller spaces and younger children. This compact bouncer provides all the fun of a full-size unit in a more manageable footprint, making it ideal for indoor events, smaller backyards, or venues with space constraints.",
    width: "15'",
    length: "15'",
    height: "15'",
    spaceRequired: "20' x 20'",
    capacityAges2to4: "6-8 kids",
    capacityAges4to7: "5-7 kids",
    capacityAges7to10: "4-6 kids",
    capacityAges10Plus: "4 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 3,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "jumbo-castle-bouncer",
    description: "Measuring 20 feet by 20 feet of jumping space, our Jumbo Castle Bounce House rental is sure to be a hit for any event! This extra-large bouncer provides maximum space for parties with lots of kids.",
    width: "20'",
    length: "20'",
    height: "17'",
    spaceRequired: "25' x 25'",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "7-10 kids",
    capacityAges7to10: "6-9 kids",
    capacityAges10Plus: "5-7 kids",
    adultsAllowed: false,
    priceNote: "Estimated price based on location",
  },

  // Combo Bouncers
  {
    slug: "excalibur-4-in-1-castle",
    description: "This 15' x 15' bounce house features a jumping area, climbing ladder, slide and basketball hoop. The unit offers versatility for various age groups, with a steep slide that appeals to older children while remaining accessible for younger ones. It can even be set up indoors and showcases primary colors suitable for all guests.\n\nBest for children ages 5 and up who want slide entertainment.",
    width: "15'",
    length: "16'",
    height: "16'",
    spaceRequired: "20' x 20'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, climbing ladder, slide, and basketball hoop",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "disney-princess-3d-5-in-one",
    description: "Our Disney Princess Collection 3D 5-In-One combo bouncer brings the magic of Disney to your party! Features a spacious jumping area, climbing wall, slide, basketball hoop, and obstacles. The beautiful princess theming makes it perfect for any little royal's celebration.\n\nBest for children ages 5 and up who want multiple activities.",
    width: "16'",
    length: "20'",
    height: "15'",
    spaceRequired: "21' x 25'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, climbing wall, slide, basketball hoop, and obstacles",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "5-in-one-modular-combo",
    description: "Our 5-In-One Modular Combo bouncer provides five activities in one unit! Features a jumping area, climbing wall, slide, basketball hoop, and obstacles. The versatile design keeps kids entertained for hours with multiple ways to play.\n\nBest for children ages 5 and up who want multiple activities.",
    width: "16'",
    length: "20'",
    height: "15'",
    spaceRequired: "21' x 25'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, climbing wall, slide, basketball hoop, and obstacles",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "wacky-kid-zone",
    description: "This combo bounce house features spacious bouncing areas with an Entanglement game mat, climbing and sliding lanes, and an X-TRA Grip climb cover for safety. The 56-inch-high walls enclose an interior bouncing area of 10'x7', complete with a basketball hoop and obstacles. 360-degree mesh sides allow parent supervision.\n\nDesigned for children ages 3 and up who want a slide, hoops, obstacles… and fun!",
    width: "16'",
    length: "16'",
    height: "10' 6\"",
    spaceRequired: "21' x 21'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-12 kids",
    capacityAges4to7: "6-10 kids",
    capacityAges7to10: "5-8 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "150 lbs/person",
    adultMaxCount: 6,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, slide, dual basketball hoops (inside and outside), ladder to slide, and obstacles",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "jump-n-splash-castle",
    description: "Tons of fun all in one! Our Jump N Splash Castle with Pool contains a jumping area, basketball hoop, climbing ladder and slide as well as a detachable pool. Features a non-slip vinyl surface and can operate either wet or dry, making it versatile for various party settings.\n\nGreat for warm weather events!",
    width: "17'",
    length: "27'",
    height: "18'",
    spaceRequired: "20' x 25'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: false,
    canUseWater: true,
    hasPool: true,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, basketball hoop, climbing ladder, slide, and detachable pool",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "jump-n-splash-paradise-palms",
    description: "Tons of fun all in one! Our Jump N Splash Paradise Palms bounce house contains a jumping area, basketball hoop, climbing ladder and slide as well as a detachable pool. Functions in wet or dry modes, featuring a non-slip vinyl surface that prevents slipping during water play.\n\nPerfect for tropical-themed parties!",
    width: "17'",
    length: "27'",
    height: "18'",
    spaceRequired: "20' x 25'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: false,
    canUseWater: true,
    hasPool: true,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, basketball hoop, climbing ladder, slide, and detachable pool",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "balloon-ride-5-in-one",
    description: "Our 5-In-One Balloon Ride Bouncer features a colorful hot air balloon theme with a spacious jumping area, climbing wall, slide, basketball hoop, and obstacles. The whimsical design captures the imagination while providing hours of active fun.\n\nBest for children ages 3 and up who want multiple activities.",
    width: "16'",
    length: "20'",
    height: "15'",
    spaceRequired: "21' x 25'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasBasketballHoop: true,
    hasClimbingWall: true,
    comboFeatures: "Jumping area, climbing wall, slide, basketball hoop, and obstacles",
    priceNote: "Estimated price based on location",
  },

  // Wet/Dry Slides
  {
    slug: "22-dry-slide",
    description: "Jersey Jumpy's 22' EZ slide bounce house will be the life of the party! Climb up and slide down this thrilling slide. Great for block parties and school field days, keeping children actively entertained.\n\nAs seen on The Real Housewives of New Jersey!\n\nRecommended for ages 5 and up with a minimum height requirement of 36 inches. Adult supervision is mandatory.",
    width: "18'",
    length: "36'",
    height: "22'",
    spaceRequired: "35' x 40'",
    heightRequirement: "36\" minimum",
    adultsAllowed: true,
    adultWeightLimit: "175 lbs/person",
    adultMaxCount: 1,
    hasSlide: true,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "18-dual-lane-slide",
    description: "Our 18' Dual Lane Slide lets two riders race down side by side! Perfect for competitive fun at parties and events. The dual lanes keep the action going with less waiting time.\n\nRecommended for ages 5 and up. Adult supervision is required.",
    width: "18'",
    length: "30'",
    height: "18'",
    spaceRequired: "30' x 35'",
    heightRequirement: "36\" minimum",
    adultsAllowed: true,
    adultWeightLimit: "175 lbs/person",
    adultMaxCount: 2,
    hasSlide: true,
    priceNote: "Estimated price based on location",
  },
  {
    slug: "hawaiian-splash",
    description: "Jersey Jumpy's Hawaiian splash water bounce slide features vibrant tropical design with fire, brown and green marble colored vinyl and palm trees, making it ideal for summer events. The unit includes a detachable 10-foot pool that can be removed for dry-slide use.\n\nRecommended for ages 5 and up with a 42\" minimum height requirement. An attendant must supervise the slide at all times.",
    width: "30'",
    length: "10'",
    height: "18'",
    spaceRequired: "35' x 18'",
    heightRequirement: "42\" minimum",
    adultsAllowed: true,
    adultWeightLimit: "175 lbs/person",
    adultMaxCount: 1,
    canUseWater: true,
    hasPool: true,
    hasSlide: true,
    priceNote: "$550 dry / $700 wet - Estimated price based on location",
  },
  {
    slug: "fire-n-ice",
    description: "Jersey Jumpy's two-story bounce slide is ideal for any celebration! Kids can choose if they would like to slide down from 9' or continue up the ladder to slide down from the 12' platform. Features a detachable pool for water play.\n\nRecommended for ages 5 and up with a 42\" minimum height requirement. An attendant must supervise the slide at all times.",
    width: "34'",
    length: "17'",
    height: "20'",
    spaceRequired: "35' x 18'",
    heightRequirement: "42\" minimum",
    adultsAllowed: true,
    adultWeightLimit: "175 lbs/person",
    adultMaxCount: 1,
    canUseWater: true,
    hasPool: true,
    hasSlide: true,
    priceNote: "$675 dry / $800 wet - Estimated price based on location",
  },
  {
    slug: "wild-wave-jr",
    description: "This water slide can be used both as water slides or dry slides! Features one slide lane with a waving surface and a climbing lane equipped with X-TRA Grip covers designed to minimize slips and enhance safety. A fun way to stay cool when using wet and a good way to level up your party!\n\nRecommended for ages 5 and up with a 34\" minimum height requirement.",
    width: "12'",
    length: "26'",
    height: "14'",
    spaceRequired: "32' x 18'",
    heightRequirement: "34\" minimum",
    adultsAllowed: true,
    adultWeightLimit: "150 lbs/person",
    adultMaxCount: 1,
    canUseWater: true,
    hasSlide: true,
    priceNote: "$475 dry / $650 wet - Estimated price based on location",
  },

  // Obstacle Courses
  {
    slug: "40-obstacle-challenge",
    description: "Obstacle course challenge enthusiasts will love Jersey Jumpy's 40' inflatable obstacle course. This colorful course features two slides with wide easy-to-climb steps and entrance doors accessible to all. Run, jump and climb your way through this amazing inflatable obstacle challenge!\n\nSafety screen mesh is used extensively throughout, making this unit the safest on the market. Perfect for indoor play facilities as well.\n\nMinimum height of 42\" required due to stairs within the course.",
    width: "12'",
    length: "40'",
    height: "15'",
    spaceRequired: "50' x 15'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasClimbingWall: true,
    comboFeatures: "Two slides, climbing areas, obstacles, and dual-lane design for staggered entry",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "50-obstacle-challenge",
    description: "Take your party to the next level with our 50' Obstacle Challenge! This longer course features more obstacles and challenges than the 40' version, including two slides with wide easy-to-climb steps. The dual-lane design allows staggered entry, preventing crowding.\n\nSafety screen mesh is used extensively throughout. Perfect for larger events and competitive fun.\n\nMinimum height of 42\" required due to stairs within the course.",
    width: "12'",
    length: "50'",
    height: "15'",
    spaceRequired: "60' x 15'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasClimbingWall: true,
    comboFeatures: "Two slides, climbing areas, extended obstacle zones, and dual-lane design",
    priceNote: "Estimated price based on location",
  },
  {
    slug: "65-mega-obstacle",
    description: "Take the mega obstacle course challenge today! This inflatable obstacle course features two slides with wide easy-to-climb steps and entrance doors accessible to all. You can mix and match the three sections to create a 65' long obstacle course or use modules one and two for an exciting 40' course.\n\nSafety screen mesh is used extensively throughout all three modules, making this unit the safest on the market. Particularly suited for indoor play centers and large outdoor events.\n\nMinimum height of 42\" required due to stairs within the course.",
    width: "12'",
    length: "65'",
    height: "15'",
    spaceRequired: "75' x 15'",
    heightRequirement: "42\" minimum",
    capacityAges2to4: "8-10 kids",
    capacityAges4to7: "6-8 kids",
    capacityAges7to10: "4-7 kids",
    capacityAges10Plus: "4-6 kids",
    adultsAllowed: true,
    adultWeightLimit: "180 lbs/person",
    adultMaxCount: 4,
    hasSlide: true,
    hasClimbingWall: true,
    comboFeatures: "Modular three-section design, two slides, climbing areas, extensive obstacle zones, and dual-lane design",
    priceNote: "Estimated price based on location",
  },
];

async function updateDescriptions() {
  console.log("Starting inflatable description updates...\n");

  let updated = 0;
  let notFound = 0;

  for (const update of inflatableUpdates) {
    const { slug, ...data } = update;

    try {
      const result = await db
        .update(schema.inflatables)
        .set(data)
        .where(eq(schema.inflatables.slug, slug));

      console.log(`  ✓ Updated: ${slug}`);
      updated++;
    } catch (error) {
      console.error(`  ✗ Error updating ${slug}:`, error);
      notFound++;
    }
  }

  console.log(`\nUpdate complete!`);
  console.log(`  Updated: ${updated}`);
  console.log(`  Errors: ${notFound}`);
}

updateDescriptions()
  .then(() => {
    console.log("\nScript finished successfully.");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Script failed:", error);
    process.exit(1);
  });
